# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:32
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models
from django.utils import timezone
import uuid


def load_regions(apps, schema_editor):
    call_command('loaddata', 'regions')


def load_positions(apps, schema_editor):
    call_command('loaddata', 'positions')


def load_brackets(apps, schema_editor):
    call_command('loaddata', 'skill_brackets')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('secondary', models.BooleanField(default=False, help_text='Designates whether this position is only useful in the context of a team member, but not a Team or a Player alone (e.g. Coach or Standin).')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillBracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=timezone.now)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['team', 'player'],
            },
        ),
        migrations.RunPython(load_regions, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_positions, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_brackets, reverse_code=migrations.RunPython.noop),
    ]
