# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
        ('common', '0002_auto_20160804_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('started', models.DateTimeField(verbose_name='Started')),
                ('ended', models.DateTimeField(verbose_name='Ended')),
                ('reason', models.IntegerField(choices=[(1, 'Left'), (2, 'Removed')], help_text='Reason for leaving the team', null=True, verbose_name='Reason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
