# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 01:24
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Region = apps.get_model('common.Region')
    regions_to_add = ['SE Asia', 'Australia', 'South Korea']

    for region in regions_to_add:
        try:
            Region.objects.get(name=region)
        except Region.DoesNotExist:
            Region.objects.create(name=region)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20161127_1754'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
