# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170410_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('to', models.TextField()),
                ('from_address', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('text_content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
