# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 21:52
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Region = apps.get_model('common.Region')
    region_to_add = 'China'
    try:
        Region.objects.get(name=region_to_add)
    except Region.DoesNotExist:
        Region.objects.create(name=region_to_add)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_emailrecord'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
