# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 21:56
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_interests(apps, schema_editor):
    call_command('loaddata', 'interests')


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170624_2156'),
    ]

    operations = [
        migrations.RunPython(load_interests, reverse_code=migrations.RunPython.noop),
    ]
