# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 23:00
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_languages(apps, schema_editor):
    call_command('loaddata', 'languages')


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_language'),
    ]

    operations = [
        migrations.RunPython(load_languages, reverse_code=migrations.RunPython.noop),
    ]
