# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_populate_interests'),
        ('teams', '0003_auto_20170624_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='teams', to='common.Interest'),
        ),
    ]
