# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_populate_languages'),
        ('teams', '0004_team_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='teams', to='common.Language'),
        ),
    ]
