# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
