# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20171008_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='search_score',
            field=models.IntegerField(default=0),
        ),
    ]
