# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20170604_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mmr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mmr_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mmr_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
