# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_populate_interests'),
        ('players', '0004_auto_20170623_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='players', to='common.Interest'),
        ),
    ]
