# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
