# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-15 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(choices=[(0, 'All'), (1, 'Updates and New Features'), (2, 'Player Notifications'), (3, 'Team Notifications')])),
                ('receive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emailpreference',
            name='user_email_preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='tf_auth.UserEmailPreferences'),
        ),
        migrations.AlterUniqueTogether(
            name='emailpreference',
            unique_together=set([('tag', 'user_email_preferences')]),
        ),
    ]
