# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-15 17:10
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    TFUser = apps.get_model('tf_auth.TFUser')
    UserEmailPreferences = apps.get_model('tf_auth.UserEmailPreferences')

    for user in TFUser.objects.all():
        try:
            user.user_email_preferences
        except UserEmailPreferences.DoesNotExist:
            UserEmailPreferences.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0002_auto_20170415_1710'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
