# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0004_auto_20170416_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfuser',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='username'),
        ),
    ]
