# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0005_tfuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
