# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0006_auto_20170416_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfuser',
            name='steamid',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Steam ID'),
        ),
    ]
