# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0009_populate_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
