# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 22:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0010_auto_20170420_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfuser',
            options={'ordering': ('username',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='tfuser',
            name='steam_friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=[], size=None),
        ),
    ]
