# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 17:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Bug'), (1, 'Feature request'), (2, 'Comment')])),
                ('comments', models.CharField(max_length=2048)),
                ('url', models.URLField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('redux_state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
